SegundoObligatiorioP3/SegundoObligatorio/Controllers/PlantasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataAccess.Contexto;
using Dominio;
using Dominio.InterfacesRepositorio;
using SegundoObligatorio.Models;
using Microsoft.AspNetCore.Http;

namespace SegundoObligatorio.Controllers
{
    public class PlantasController : Controller
    {
        private readonly IRepositorioPlanta _repoPlanta;
        private readonly IRepositorioTipoPlanta _repoTipo;



        public PlantasController(IRepositorioPlanta repoPlanta, IRepositorioTipoPlanta repoTipo)
        {
            _repoPlanta = repoPlanta;
            _repoTipo = repoTipo;
        }

        // GET: Plantas
        public IActionResult Index()
        {
            string nombre = HttpContext.Session.GetString("usuario");
            if (nombre != null)
            {
                ViewBag.Mensaje = "No se encontraron Plantas";
            


            IEnumerable<Planta> misPlantas = _repoPlanta.FindAll();
            if (misPlantas != null)
                return View(misPlantas);
            else
               
            return View(ViewBag.Mensaje);
            }
            return View("~/Views/Home/Index.cshtml");
        }

        // GET: Plantas/Details/5
        public IActionResult Details(int? id)
        {
            string nombre = HttpContext.Session.GetString("usuario");
            if (nombre != null)
            {
                if (id == null)
            {
                return NotFound();
            }

            var planta = _repoPlanta.FindById(id);
            if (planta == null)
            {
                return NotFound();
            }

            return View(planta);
            }
            return View("~/Views/Home/Index.cshtml");
        }

        // GET: Plantas/Create
        public IActionResult Create()
        {
            string nombre = HttpContext.Session.GetString("usuario");
            if (nombre != null)
            {
                ViewBag.Tipos = _repoTipo.FindAll();
            if (ViewBag.Retorno != null)
            { 
                     ViewBag.Tipos = _repoTipo.FindAll(); 
                return View(ViewBag.Retorno);}
            return View();
            }
            return View("~/Views/Home/Index.cshtml");
        }

        // POST: Plantas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Planta planta)
        {
            try
            {
                string nombre = HttpContext.Session.GetString("usuario");
                if (nombre != null)
                {
                    if (ModelState.IsValid) 
                {
                    if (!System.Text.RegularExpressions.Regex.IsMatch(planta.NombreCientifico,
                                           "^[a-zA-Z'.]$")) 
                    {
                        ViewBag.Retorno = "Error - Nombre no puede contener numeros";
                        ViewBag.Tipos = _repoTipo.FindAll();
                    }
                    if (_repoPlanta.FindByName(planta.NombreCientifico) != null) 
                    {
                        ViewBag.Retorno = "Erro1r - Ya existe planta con ese Nombre Cientifico";
                        ViewBag.Tipos = _repoTipo.FindAll();
                    }
                    return View();
                }
                _repoPlanta.Add(planta);
                return RedirectToAction(nameof(Index));
                }
                return View("~/Views/Home/Index.cshtml");

            }
            catch (Exception)
            {

                return View("Error", new ErrorViewModel() { RequestId = planta.IdPlanta.ToString() });
            }
        }

        // GET: Plantas/Edit/5
        public IActionResult Edit(int? id)
        {
            string nombre = HttpContext.Session.GetString("usuario");
            if (nombre != null)
            {
                if (id == null)
            {
                return NotFound();
            }

            var planta = _repoPlanta.FindById(id);
            if (planta == null)
            {
                return NotFound();
            }
            ViewBag.Tipos = _repoTipo.FindAll();
            return View(planta);
            }
            return View("~/Views/Home/Index.cshtml");
        }

        // POST: Plantas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Planta planta)
        {
            try
            {
                string nombre = HttpContext.Session.GetString("usuario");
                if (nombre != null)
                {
                    if (ModelState.IsValid)
                {
                    _repoPlanta.Update(planta);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View(planta);

                    }
                }
                return View("~/Views/Home/Index.cshtml");
            }
            catch (Exception)
            {
                return View("Error", new ErrorViewModel() { RequestId = planta.IdPlanta.ToString() });
            }
        }

        // GET: Plantas/Delete/5
        public IActionResult Delete(int? id)
        {
            string nombre = HttpContext.Session.GetString("usuario");
            if (nombre != null)
            {
                if (id == null)
            {
                return NotFound();
            }

            var planta = _repoPlanta.FindById(id);
            if (planta == null)
            {
                return NotFound();
            }

            return View(planta);
            }
            return View("~/Views/Home/Index.cshtml");
        }

        [HttpPost]
        public ActionResult BuscarPlanta(int id, string texto)
        {
            string nombre = HttpContext.Session.GetString("usuario");
            if (nombre != null)
            {
                ViewBag.Mensaje = "No se encontraron Plantas";



                IEnumerable<Planta> misPlantas = (_repoPlanta.Buscar(texto, id));
                if (misPlantas != null)
                    return View(misPlantas);
                else

                    return View(ViewBag.Mensaje);
            }
            else
            {

                return View("~/Views/Home/Index.cshtml");


            }

        }
        // POST: Plantas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            try
            {
                string nombre = HttpContext.Session.GetString("usuario");
                if (nombre != null)
                {
                    var planta = _repoPlanta.FindById(id);
                if (planta != null)
                {
                    _repoPlanta.Remove(planta);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return NotFound();
                    }
                }
                return View("~/Views/Home/Index.cshtml");
            }
            catch (Exception)
            {
                return View("Error", new ErrorViewModel() { RequestId = id.ToString() });
            }


        }

        
    }
}

SegundoObligatiorioP3/SegundoObligatorio/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataAccess.Contexto;
using Dominio;
using Dominio.InterfacesRepositorio;
using SegundoObligatorio.Models;
using Microsoft.AspNetCore.Http;

namespace SegundoObligatorio.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly IRepositorioUsuario _repoUsu;

        public UsuariosController(IRepositorioUsuario repoUsu)
        {
            _repoUsu = repoUsu;
        }


        // GET: Usuarios
        public IActionResult Index()
        {
            return View("~/Login");

        }
        public IActionResult Login()
        {
            return View();
            //  return View("~/Views/Home/Index.cshtml");
        }

        [HttpPost]
        public ActionResult Login(string usu, string pass)
        {
            if (usu != "" && pass != "")
            {
                Usuario miUsu = _repoUsu.Login(usu, pass);
                if (miUsu != null)
                {
                    TempData["usuario"] = usu;
                    HttpContext.Session.SetString("usuario", usu);
                    return View("~/Views/Home/Index.cshtml");
                }
                else
                {
                    return View();
                }

            }
            else
            {
                return View("Index");
            }
        }

        public ActionResult LogOut()
        {

            HttpContext.Session.Clear();
            TempData["usuario"] = null;
            return View("~/Views/Home/Index.cshtml");
        }

        [HttpPost]
        public IActionResult AgregarPred() 
        {
            _repoUsu.AddUsers();
            return View("~/Views/Home/Index.cshtml");
        }

        //----------------------------------------------------------//

        // GET: Usuarios/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = _repoUsu.FindById(id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // GET: Usuarios/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Usuarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Usuario miUsu)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _repoUsu.Add(miUsu);
                    return RedirectToAction(nameof(Index));
                }
                return View(miUsu);
            }
            catch (Exception)
            {

                return View("Error", new ErrorViewModel() { RequestId = miUsu.IdUsuario.ToString() });
            }
        }

        // GET: Usuarios/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = _repoUsu.FindById(id);
            if (usuario == null)
            {
                return NotFound();
            }
            return View(usuario);
        }

        // POST: Usuarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Usuario miUsu)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _repoUsu.Update(miUsu);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View(miUsu);

                }
            }
            catch (Exception)
            {
                return View("Error", new ErrorViewModel() { RequestId = miUsu.IdUsuario.ToString() });
            }
        }

        // GET: Usuarios/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tipo = _repoUsu.FindById(id);
            if (tipo == null)
            {
                return NotFound();
            }

            return View(tipo);
        }

        // POST: Plantas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            int miId = Convert.ToInt32(ViewBag.id);
            try
            {
                var tipo = _repoUsu.FindById(id);
                if (tipo != null)
                {
                    _repoUsu.Remove(tipo);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return NotFound();
                }
            }
            catch (Exception)
            {
                return View("Error", new ErrorViewModel() { RequestId = id.ToString() });
            }

        }
    }
}

SegundoObligatiorioP3/SegundoObligatorio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SegundoObligatorio</title>
    <link href="./favicon.ico" rel="favicon" type="image/x-icon" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
 
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container"  >
                <img src="~/assets/logo.svg" width="40" height="40" class="d-inline-block align-top mr-2" alt="">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" >SegundoObligatorio</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                       @if (TempData["usuario"] != null)
                       {
                            <li class="nav-item dropdown">
                                
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Plantas
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">


                                    <a class="nav-link text-dark" asp-area="" asp-controller="Plantas" asp-action="Index">Listado Plantas</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Plantas" asp-action="Create">Agregar Planta</a>

                                </div>

                            </li>

                        <li class="nav-item dropdown" id="nombre">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Tipo de Plantas
                            </a>

                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                                <a class="nav-link text-dark" asp-area="" asp-controller="TipoPlantas" asp-action="Index">Listar Tipo</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="TipoPlantas" asp-action="Create">Agregar Tipo</a>

                            </div>
                        </li>
                       }
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Cuenta
                            </a>
                            
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                @if (TempData["usuario"] == null)
                                {
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Login">Login</a>}
                                else
                                {
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="LogOut">Logout</a>}
                            </div>
                        </li>

                        
                    </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2022 - SegundoObligatorio - @TempData["usuario"]
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
    </body>



</html>